replicaCount: 1

# just to use if condtion - go templeting
owner: ""
url: ""

image:
  repository: docker.io/matar86/myimdb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2"

ports:
  - name: http
    containerPort: 5000
    protocol: TCP

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 5000

resources:
  limits:
    cpu: 20m
    memory: 50Mi
  requests:
    cpu: 10m
    memory: 50Mi