apiVersion: apps/v1
kind: Deployment
metadata:
  #name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ printf "%s-%s" .Release.Name .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    owner: {{ default "Matar" .Values.owner | quote }}
    github: "mataralhawiti/myimdb"
    # use go-template if
    {{- if .Values.url}}
    url: {{ .Values.url | quote}}
    {{- else}}
    url: "https://myimdbmovies.azurewebsites.net/"
    {{- end}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: myimdbapp
          #image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          ports:
            # use range funtion (loop)
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}