apiVersion: v1
kind: Service
metadata:
  name: {{ include "myimdb.fullname" . }}
  labels:
    {{- include "myimdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: tcp
  selector:
    {{- include "myimdb.selectorLabels" . | nindent 4 }}
