apiVersion: v1
kind: Service
metadata:
  #name: {{ printf "%s-%s" .Release.Name .Chart.Name }}
  # we can use Template Macro here (_helper.tpl)
  name: {{ template "myimdb.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
