apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimdb
  labels:
    app: myimdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myimdb
  template:
    metadata:
      labels:
        app: myimdb
    spec:
      containers:
        - name: myimdbapp
          image: docker.io/matar86/myimdb:v2
          resources:
            limits:
              cpu: "20m"
              memory: "50Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
