apiVersion: v1
kind: Service
metadata:
  name: myimdb
  labels:
    app: myimdb
spec:
  selector:
    app: myimdb
  type: NodePort #LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
